version: '3'

services:
  backend:
    build: ./backend
    restart: "unless-stopped"
  frontend:
    build: ./frontend
    restart: "unless-stopped"
    ports:
      - 8082:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d



